#!/bin/bash
echo "enter first number "
read a
echo "enter second number "
read b
if [[ $a -gt $b ]]
then
echo "$a is greater number "
elif [[ $a -eq $b ]]
then
echo "both are equal"
elif [[ $b -gt $a ]]
then
echo "$b is greater "
fi
